from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from typing import List
from app.database import db
from app.utils.deps import get_current_admin_user
from pydantic import BaseModel
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO

router = APIRouter()

class AuditLogEntry(BaseModel):
    id: str
    timestamp: datetime
    user: str
    action: str
    resource: str
    details: str
    ipAddress: str
    status: str
    severity: str

@router.get("/", response_model=List[AuditLogEntry])
async def get_audit_logs(limit: int = 100, current_user = Depends(get_current_admin_user)):
    cursor = db.audit_logs.find().sort("timestamp", -1).limit(limit)
    logs = []
    async for log in cursor:
        log["id"] = str(log["_id"])
        logs.append(log)
    return logs

@router.get("/export")
async def export_audit_logs(current_user = Depends(get_current_admin_user)):
    logs = await db.audit_logs.find().sort("timestamp", -1).limit(1000).to_list(None)
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(letter),
                            leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    elements = []
    styles = getSampleStyleSheet()
    
    # Header
    header_text = f"Audit Log Report - Generated by {current_user.get('username', 'Admin')}"
    elements.append(Paragraph(header_text, styles['Heading1']))
    elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # Table Data
    data = [["Timestamp", "User", "Action", "Resource", "Status", "Severity"]]
    for log in logs:
        ts = log.get("timestamp")
        if isinstance(ts, datetime):
            ts = ts.strftime("%Y-%m-%d %H:%M:%S")
        else:
            ts = str(ts)
            
        data.append([
            ts,
            log.get("user", "Unknown"),
            log.get("action", "Unknown"),
            log.get("resource", "Unknown"),
            log.get("status", "Unknown"),
            log.get("severity", "Unknown")
        ])
        
    table = Table(data, colWidths=[110, 100, 120, 120, 80, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    
    elements.append(table)
    doc.build(elements)
    buffer.seek(0)
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=audit_report.pdf"}
    )
